fs = 1e6; %sampling frequency
nyquist = fs / 2; % Nyquist frequency (500 kHz)
f_lower = 200e3/nyquist; % Lower cutoff frequency
f_upper = 300e3/nyquist; % Upper cutoff frequency
bpFilt = designfilt('bandpassiir', ...
    'FilterOrder', 6, ...
    'HalfPowerFrequency1', f_lower, ...
    'HalfPowerFrequency2', f_upper, ...
    'SampleRate', fs);

filtered_signal = filter(bpFilt, received_signal);
